#!/bin/bash
#
# Resource script for zabbix daemon
#
# Description:  Manages zabbix daemon as an OCF resource in
#               an High Availability setup.
#
#       usage: $0 {start|stop|status|monitor|validate-all|meta-data}
#
#       The "start" arg starts samba.
#
#       The "stop" arg stops it.
#
# OCF parameters:
# OCF_RESKEY_scriptpath
# OCF_RESKEY_conffile
# OCF_RESKEY_extraconf
#
# Note:This RA requires that the samba config files has a "pidfile"
# entry so that it is able to act on the correct process
##########################################################################
# Initialization:

: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/resource.d/heartbeat}
. ${OCF_FUNCTIONS_DIR}/.ocf-shellfuncs

USAGE="Usage: $0 {start|stop|status|monitor|validate-all|meta-data}";

##########################################################################

usage()
{
        echo $USAGE >&2
}

meta_data()
{
cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="zabbix">
<version>1.0</version>
<longdesc lang="en">
This script manages zabbix daemon
</longdesc>
<shortdesc lang="en">Manages an zabbix daemon</shortdesc>

<parameters>

<parameter name="scriptpath">
<longdesc lang="en">
The zabbix script path.
For example, "/etc/init.d/zabbix-server"
</longdesc>
<shortdesc lang="en">Full path to the zabbix script</shortdesc>
<content type="string" default="/etc/init.d/zabbix-server"/>
</parameter>

<parameter name="conffile">
<longdesc lang="en">
The samba daemon configuration file name with full path.
For example, "/etc/zabbix/zabbix_server.conf"
</longdesc>
<shortdesc lang="en">Configuration file name with full path</shortdesc>
<content type="string" default="/etc/zabbix/zabbix_server.conf" />
</parameter>

</parameters>

<actions>
<action name="start" timeout="20s"/>
<action name="stop" timeout="20s"/>
<action name="monitor" depth="0" timeout="20s" interval="60s" />
<action name="validate-all" timeout="20s"/>
<action name="meta-data"  timeout="5s"/>
</actions>
</resource-agent>
END
exit $OCF_SUCCESS
}

get_pid_and_conf_file()
{
        if [ -n "$OCF_RESKEY_conffile" ]; then
                CONF_FILE=$OCF_RESKEY_conffile
        else
                CONF_FILE="/etc/zabbix/zabbix_server.conf"
        fi

        PIDFILE="`grep -v \"#\" ${CONF_FILE} | grep \"pidfile\" | sed 's/^[ \t]*pidfile[ \t]*//'`"
        if [ "${PIDFILE}" = '' ]; then
                PIDFILE="/var/run/zabbix/zabbix_server.pid"
        fi
}

zabbix_status()
{
        if [ -n "$PIDFILE" -a -f "$PIDFILE" ]; then
                # zabbix is probably running
                PID=`cat $PIDFILE`
                if [ -n "$PID" ]; then
                        if ps -p $PID | grep zabbix_server >/dev/null ; then
                                ocf_log info "info zabbix daemon running"
                                return $OCF_SUCCESS
                        else
                                ocf_log info "zabbix daemon is not running but pid file exists"
                                return $OCF_NOT_RUNNING
                        fi
                else
                        ocf_log err "PID file empty!"
                        return $OCF_ERR_GENERIC
                fi
        fi

        # zabbix is not running
        ocf_log info "zabbix daemon is not running"
        return $OCF_NOT_RUNNING
}

zabbix_start()
{
        # if zabbix is running return success
        zabbix_status
        retVal=$?
        if [ $retVal -eq $OCF_SUCCESS ]; then
                exit $OCF_SUCCESS
        elif [ $retVal -ne $OCF_NOT_RUNNING ]; then
                ocf_log err "Error. Unknown status."
                exit $OCF_ERR_GENERIC
        fi

        if [ -n "$OCF_RESKEY_scriptpath" ]; then
                COMMAND="$OCF_RESKEY_scriptpath"
        else
                COMMAND="service zabbix-server start"
        fi

        $COMMAND
        if [ $? -ne 0 ]; then
                ocf_log err "Error. zabbix daemon returned error $?."
                exit $OCF_ERR_GENERIC
        fi

        ocf_log info "Started zabbix daemon."
        exit $OCF_SUCCESS
}


zabbix_stop()
{
        if zabbix_status ; then
                PID=`cat $PIDFILE`
                if [ -n "$PID" ] ; then
                        #kill $PID
                        service zabbix-server stop
                        if [ $? -ne 0 ]; then
                                kill -SIGKILL $PID
                                if [ $? -ne 0 ]; then
                                        ocf_log err "Error. Could not stop zabbix daemon."
                                        return $OCF_ERR_GENERIC
                                fi
                        fi
                        rm $PIDFILE 2>/dev/null
                fi
        fi
        ocf_log info "Stopped zabbix daemon."
        exit $OCF_SUCCESS
}

zabbix_monitor()
{
        zabbix_status
}

msyql_validate_all()
{
        if [ -n "$OCF_RESKEY_scriptpath" -a ! -x "$OCF_RESKEY_scriptpath" ]; then
                ocf_log err "Script path $OCF_RESKEY_scriptpath does not exist."
                exit $OCF_ERR_ARGS
        fi
        if [ -n "$OCF_RESKEY_conffile" -a ! -f "$OCF_RESKEY_conffile" ]; then
                ocf_log err "Config file $OCF_RESKEY_conffile does not exist."
                exit $OCF_ERR_ARGS
        fi

        #if  grep -v "^#" "$CONF_FILE" | grep "pidfile" > /dev/null ; then
        #        :
        #else
        #        ocf_log err "Error. \"pidfile\" entry required in the samba config file by samba OCF RA."
        #        return $OCF_ERR_GENERIC
        #fi

        return $OCF_SUCCESS
}


#
# Main
#

if [ $# -ne 1 ]; then
        usage
        exit $OCF_ERR_ARGS
fi

case $1 in
        start)  get_pid_and_conf_file
                zabbix_start
                ;;

        stop)   get_pid_and_conf_file
                zabbix_stop
                ;;

        status) get_pid_and_conf_file
                zabbix_status
                ;;

        monitor)get_pid_and_conf_file
                zabbix_monitor
                ;;

        validate-all)   get_pid_and_conf_file
                        zabbix_validate_all
                        ;;

        meta-data)      meta_data
                        ;;

        usage)  usage
                exit $OCF_SUCCESS
                ;;

        *)      usage
                exit $OCF_ERR_UNIMPLEMENTED
                ;;
esac
