#https://bestmonitoringtools.com/how-to-install-zabbix-server-on-ubuntu/
- hosts: zabbix01
  become: yes
  tasks:
    - name: Disable service systemd-resolved
      service:
        name: systemd-resolved.service
        enabled: no

    - name: Stop systemd-resolved
      service:
        name: systemd-resolved.service
        state: stopped

    - name: Disable service apache2
      service:
        name: apache2.service
        enabled: no

    - name: Remove resolv.conf managed
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent

    - name: Creating a file with content
      copy:
        dest: "/etc/resolv.conf"
        content: |
          nameserver {{ name_server }}
          search {{ domain_name }}

#    - name: Restart network-manager
#      service:
#        name: network-manager.service
#        state: restarted
