#https://bestmonitoringtools.com/how-to-install-zabbix-server-on-ubuntu/
- hosts: all
  become: yes
  tasks:
    - name: "Install Zabbix Server"
      apt:
       name: zabbix-server-mysql
       state: present
       update_cache: true

    - name: "Install Zabbix Frontend"
      apt:
       name: zabbix-frontend-php
       state: present
       update_cache: true

    - name: "Install Apache"
      apt:
       name: zabbix-apache-conf
       state: present
       update_cache: true

    - name: Create Gluster Zabbix MySQL volume
      shell: "gluster volume create volume-zabbix {{ gluster_replica }} force > zabbix-gluster-volume.txt"
      args:
        chdir: $HOME
        creates: zabbix-gluster-volume.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

    - name: Start Gluster Zabbix MySQL volume
      shell: "gluster volume start volume-zabbix > zabbix-gluster-start-volume.txt"
      args:
        chdir: $HOME
        creates: zabbix-gluster-start-volume.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

    - name: Create Zabbix MySQL data folder
      file:
        path: /var/lib/mysql
        state: directory

    - name: Mount gluster volume
      shell: "mount -t glusterfs -o acl localhost:volume-zabbix /var/lib/mysql"
      args:
        creates: /var/lib/mysql/mysql

    - name: "Install mariadb-common"
      apt:
        name: mariadb-common
        state: present
        update_cache: true

    - name: "Install mariadb-client"
      apt:
        name: mariadb-client-10.3
        state: present
        update_cache: true

    - name: "Install mariadb-server"
      apt:
        name: mariadb-server-10.3
        state: present
        update_cache: true
      throttle: 1

    - name: Disable service mysqld
      service:
        name: mysql.service
        enabled: no

    - name: Stop mysqld
      service:
        name: mysql.service
        state: stopped

    - name: Start mysqld on the primary node
      service:
        name: mysql.service
        state: started
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

    - name: Set root pwd
      shell: "echo "UPDATE mysql.user SET Password=PASSWORD('zabbix_pwd') WHERE User='root';" | mysql -u root mysql > zabbix-mysql-root-pwd.txt"
      args:
        chdir: $HOME
        creates: zabbix-mysql-root-pwd.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

