- hosts: all
  become: yes
  tasks:
    - name: Create mnt-samba folder for snapshot
      file:
        path: /mnt/samba
        state: directory

    - name: Create mnt-shares folder for snapshot
      file:
        path: /mnt/shares
        state: directory

    - name: Move usr-local
      command: mv /usr/local /usr/local-temp

    - name: Create usr-local folder
      file:
        path: /usr/local
        state: directory

    - name: Move usr-local
      command: mount -t glusterfs -o acl localhost:volume-samba/urbackup /usr/local

    - name: Bring back usr-local content
      command: mv /usr/local-temp/* /usr/local/
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"
