- hosts: all
  become: yes
  tasks:
    - name: Create Gluster Samba internal volume
      shell: "gluster volume create volume-samba {{ gluster_replica }} force > samba-gluster-volume.txt"
      args:
        chdir: $HOME
        creates: samba-gluster-volume.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

    - name: Create Gluster Samba shares volume
      shell: "gluster volume create volume-shares {{ gluster_replica_shares }} force > samba-gluster-volume-shares.txt"
      args:
        chdir: $HOME
        creates: samba-gluster-volume-shares.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

    - name: Start Gluster Samba internal volume
      shell: "gluster volume start volume-samba > samba-gluster-start-volume.txt"
      args:
        chdir: $HOME
        creates: samba-gluster-start-volume.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

    - name: Start Gluster Samba shares volume
      shell: "gluster volume start volume-shares > samba-gluster-start-volume-shares.txt"
      args:
        chdir: $HOME
        creates: samba-gluster-start-volume-shares.txt
      when: gluster == "yes" and lb_primary == "yes"
      with_items: "{{ (gluster | default([])) and (lb_primary | default([])) }}"

    - name: Create Samba data folder
      file:
        path: /var/lib/samba
        state: directory

    - name: Create Samba shares folder
      file:
        path: /var/lib/samba-shares
        state: directory

    - name: Install packages
      command: apt-get install -y attr acl samba smbclient ldap-utils winbind libnss-winbind libpam-winbind krb5-user krb5-kdc
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Stop samba-ad-dc
      service:
        name: samba-ad-dc.service
        state: stopped

    - name: Disable service windbind
      service:
        name: winbind.service
        enabled: no

    - name: Disable service smbd
      service:
        name: smbd.service
        enabled: no

    - name: Disable service nmbd
      service:
        name: nmbd.service
        enabled: no

    - name: Delete Samba data folder
      file:
        state: absent
        path: /var/lib/samba

    - name: Recreate Samba data folder
      file:
        path: /var/lib/samba
        state: directory

    - name: Download crm samba script
      shell: "wget {{ git_source }}/samba-ad-dc/scripts/samba"
      args:
        chdir: /usr/lib/ocf/resource.d/heartbeat
        creates: /usr/lib/ocf/resource.d/heartbeat/samba

    - name: change samba script permission
      file:
        path: /usr/lib/ocf/resource.d/heartbeat/samba
        state: touch
        mode: "u=rwx,g=rx,o=rx"

    - name: Configure pacemaker Samba VIP
      shell: "crm configure primitive sambaVIP ocf:heartbeat:IPaddr2 params ip=\"{{ samba_vip_ip }}\" cidr_netmask=\"{{ samba_vip_netmask }}\" nic=\"eth0\" op monitor interval=\"10s\" meta migration-threshold=\"10\" > samba-lb-vip.txt"
      args:
        chdir: $HOME
        creates: samba-lb-vip.txt
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: Configure pacemaker Samba service
      shell: "crm configure primitive sambaSVC ocf:heartbeat:samba params conffile=/etc/samba/smb.conf op monitor interval=10s timeout=60s op start timeout=30s interval=0 op stop timeout=30s interval=0 meta migration-threshold=10 > samba-lb-service.txt"
      args:
       chdir: $HOME
       creates: samba-lb-service.txt
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: Configure pacemaker Samba group
      shell: "crm configure group grp_balancing sambaVIP sambaSVC > samba-lb-group.txt"
      args:
       chdir: $HOME
       creates: samba-lb-group.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

    - name: Configure stickiness to avoid unnecessary move on recover
      shell: "crm configure rsc_defaults resource-stickiness=100 > samba-lb-stickiness.txt"
      args:
       chdir: $HOME
       creates: samba-lb-stickiness.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

    - name: Configure samba less prefer samba-ad-dc02
      shell: "crm configure location noprefer-samba sambaSVC 5: samba-ad-dc02 > samba-lb-noprefer.txt"
      args:
       chdir: $HOME
       creates: samba-lb-noprefer.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

    - name: Configure samba prefer samba-ad-dc01
      shell: "crm configure location prefer-samba sambaSVC 50: samba-ad-dc01 > samba-lb-prefer.txt"
      args:
       chdir: $HOME
       creates: samba-lb-prefer.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"
