- hosts: active
  become: yes
  tasks:
    - name: Create Samba data folder
      file:
        path: /mnt/samba
        state: directory

    - name: Install packages
      command: apt-get install -y attr acl samba smbclient ldap-utils winbind libnss-winbind libpam-winbind krb5-user krb5-kdc
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Stop samba-ad-dc
      service:
        name: samba-ad-dc.service
        state: stopped

#    - name: Disable service windbind
#      service:
#        name: winbind.service
#        enabled: no

    - name: Disable service smbd
      service:
        name: smbd.service
        enabled: no

    - name: Disable service nmbd
      service:
        name: nmbd.service
        enabled: no

    - name: Delete Samba data folder
      file:
        state: absent
        path: /var/lib/samba

    - name: Recreate Samba data folder
      file:
        path: /var/lib/samba
        state: directory

    - name: Configure pacemaker Samba VIP
      shell: "crm node standby {{ inventory_hostname }} > samba-lb-standby.txt"
      args:
        chdir: $HOME
        creates: samba-lb-standby.txt

    - name: Download crm samba script
      shell: "wget {{ git_source }}/samba-ad-dc/scripts/sambaSVC"
      args:
        chdir: /usr/lib/ocf/resource.d/heartbeat
        creates: /usr/lib/ocf/resource.d/heartbeat/sambaSVC

    - name: change samba script permission
      file:
        path: /usr/lib/ocf/resource.d/heartbeat/sambaSVC
        state: touch
        mode: "u=rwx,g=rx,o=rx"

    - name: Configure domain name
      replace:
        path: /usr/lib/ocf/resource.d/heartbeat/sambaSVC
        regexp: 'DOMAIN:-MC.INTRANET'
        replace: 'DOMAIN:-{{ domain_name_upper }}'

    - name: Configure domain password
      replace:
        path: /usr/lib/ocf/resource.d/heartbeat/sambaSVC
        regexp: 'DOMAINPASS:-PASSWORD'
        replace: 'DOMAINPASS:-{{ domain_password }}'

    - name: Configure DNS Forwarder
      replace:
        path: /usr/lib/ocf/resource.d/heartbeat/sambaSVC
        regexp: 'DNSFORWARDER:-192.168.1.1'
        replace: 'DNSFORWARDER:-{{ dns_server }}'

    - name: Configure Samba IP
      replace:
        path: /usr/lib/ocf/resource.d/heartbeat/sambaSVC
        regexp: 'HOSTIP:-192.168.1.249'
        replace: 'HOSTIP:-{{ cluster_vip_ip }}'

    - name: "Configure Samba volume - drbd_samba_volume"
      replace:
        path: /usr/lib/ocf/resource.d/heartbeat/sambaSVC
        regexp: '<drbd_samba_volume>'
        replace: '{{ drbd_samba_volume }}' 

    - name: Configure pacemaker Samba VIP
      shell: "crm configure primitive sambaVIP ocf:heartbeat:IPaddr2 params ip=\"{{ cluster_vip_ip }}\" cidr_netmask=\"{{ cluster_vip_netmask }}\" nic=\"{{ cluster_vip_nic }}\" op monitor interval=\"10s\" meta migration-threshold=\"10\" > samba-lb-vip.txt"
      args:
        chdir: $HOME
        creates: samba-lb-vip.txt
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: Configure pacemaker Samba service
      shell: "crm configure primitive sambaSVC ocf:heartbeat:sambaSVC params conffile=/etc/samba/smb.conf op monitor interval=10s timeout=60s op start timeout=180s interval=0 op stop timeout=180s interval=0 meta migration-threshold=10 > samba-lb-service.txt"
      args:
       chdir: $HOME
       creates: samba-lb-service.txt
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: Configure pacemaker Samba group
      shell: "crm configure group grp_samba sambaVIP sambaSVC > samba-lb-group.txt"
      args:
       chdir: $HOME
       creates: samba-lb-group.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

    - name: Configure stickiness to avoid unnecessary move on recover
      shell: "crm configure rsc_defaults resource-stickiness=100 > samba-lb-stickiness.txt"
      args:
       chdir: $HOME
       creates: samba-lb-stickiness.txt
      when: lb_primary == "yes"
      with_items: "{{ (lb_primary | default([])) }}"

    #- name: Configure samba less prefer samba-ad-dc02
    #  shell: "crm configure location noprefer-samba sambaSVC 5: samba-ad-dc02 > samba-lb-noprefer.txt"
    #  args:
    #   chdir: $HOME
    #   creates: samba-lb-noprefer.txt
    #  when: lb_primary == "yes"
    #  with_items: "{{ (lb_primary | default([])) }}"

    #- name: Configure samba prefer samba-ad-dc01
    #  shell: "crm configure location prefer-samba sambaSVC 50: samba-ad-dc01 > samba-lb-prefer.txt"
    #  args:
    #   chdir: $HOME
    #   creates: samba-lb-prefer.txt
    #  when: lb_primary == "yes"
    #  with_items: "{{ (lb_primary | default([])) }}"
