#https://ltb-project.org/
- hosts: all
  become: yes
  tasks:
    - name: Download Self Service Password and unarchive
      ansible.builtin.unarchive:
        src: "{{ git_source }}/samba-ad-dc/script/ltb-project-self-service-password-1.3.tar.gz"
        dest: /usr/
        remote_src: yes

    - name: Install apache httpd
      apt:
        name: apache2
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install libapache2-mod-php
      apt:
        name: libapache2-mod-php
        state: present

    - name: Install php-ldap
      apt:
        name: php-ldap
        state: present

    - name: Install php-mbstring
      apt:
        name: php-mbstring
        state: present

    - name: Install php-pear
      apt:
        name: php-pear
        state: present

    - name: Install php-dev
      apt:
        name: php-dev
        state: present

    - name: Install libmcrypt-dev
      apt:
        name: libmcrypt-dev
        state: present

    - name: Install pecl package PHP mcrypt
      community.general.pear:
        name: pecl/mcrypt
        state: present
        prompts:
            - (.*)libmcrypt prefix? \[autodetect\]: "autodetect"

    - name: Add mcrypt extension to php.ini
      lineinfile:
        dest: "/etc/php/7.4/apache2/php.ini"
        insertafter: ';   extension=modulename'
        line: "extension=mcrypt.so"

    - name: Download config.inc.local.php
      get_url:
        url: "{{ git_source }}/samba-ad-dc/script/config.inc.local.php"
        dest: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php

    - name: "Configure ltb token"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$keyphrase = "secret";'
        replace: '$keyphrase = "{{ ltb_token }}";'

    - name: "Configure ltb binddn"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$ldap_binddn = "cn=manager,dc=example,dc=com";'
        replace: '$ldap_binddn = "{{ ltb_binddn }}";'

    - name: "Configure ltb bindpw"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$ldap_bindpw = "secret";'
        replace: '$ldap_bindpw = "{{ ltb_bindpw }}";'

    - name: "Configure ltb base"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$ldap_base = "dc=example,dc=com";'
        replace: '$ldap_base = "{{ ltb_base }}";'

    - name: "Configure ltb lang changehelp"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/lang/pt-BR.inc.php
        regexp: '\$messages\[''changehelp''\] = "Escreva a senha atual e escolha uma nova.";'
        replace: '$messages[''changehelp''] = "Digite a senha atual e escolha uma nova.";'

    - name: "Configure ltb lang changehelp"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/lang/pt-BR.inc.php
        regexp: '\$messages\[''emptychangeform''\] = "Change your password";'
        replace: '$messages[''emptychangeform''] = "Altera&ccedil;&atilde;o de senha";'

    - name: Restart Apache
      service:
        name: apache2.service
        state: restarted
