- hosts: all
  become: yes
  tasks:
    - name: Download Self Service Password and unarchive
      ansible.builtin.unarchive:
        src: "{{ git_source }}/samba-ad-dc/script/ltb-project-self-service-password-1.3.tar.gz"
        dest: /usr/
        remote_src: yes

    - name: Install Apache
      command: apt-get install -y apache2

    - name: Install PHP
      command: apt-get install -y php

    - name: Install libapache2-mod-php
      command: apt-get install -y libapache2-mod-php

