#https://ltb-project.org/
- hosts: all
  become: yes
  tasks:
    - name: Download Self Service Password and unarchive
      ansible.builtin.unarchive:
        src: "{{ git_source }}/samba-ad-dc/scripts/ltb-project-self-service-password-1.3.tar.gz"
        dest: /usr/
        remote_src: yes

    - name: Set permissions
      ansible.builtin.file: 
        path: /usr/ltb-project-self-service-password-1.3
        owner: www-data 
        group: www-data 
        recurse: yes

    - name: Install apache httpd
      apt:
        name: apache2
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install libapache2-mod-php
      apt:
        name: libapache2-mod-php
        state: present

    - name: Install php-ldap
      apt:
        name: php-ldap
        state: present

    - name: Install php-mbstring
      apt:
        name: php-mbstring
        state: present

    - name: Install php-pear
      apt:
        name: php-pear
        state: present

    - name: Install php-dev
      apt:
        name: php-dev
        state: present

    - name: Install libmcrypt-dev
      apt:
        name: libmcrypt-dev
        state: present

    - name: Install pecl package PHP mcrypt
      community.general.pear:
        name: pecl/mcrypt
        state: present
        prompts:
            - (.*)libmcrypt prefix? \[autodetect\]: "autodetect"

    - name: Download Apache Virtual Host config
      get_url:
        url: "{{ git_source }}/samba-ad-dc/configs/senha.uz.intranet.conf"
        dest: /etc/apache2/sites-available/

    - name: Enable new site
      command: /usr/sbin/a2ensite senha.uz.intranet.conf
    
    - name: Disable site default
      command: /usr/sbin/a2dissite 000-default.conf

    - name: Add mcrypt extension to php.ini
      lineinfile:
        dest: "/etc/php/7.4/apache2/php.ini"
        insertafter: ';   extension=modulename'
        line: "extension=mcrypt.so"

    - name: Download config.inc.local.php
      get_url:
        url: "{{ git_source }}/samba-ad-dc/configs/config.inc.local.php"
        dest: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php

    - name: "Configure ltb token"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$keyphrase = "secret";'
        replace: '$keyphrase = "{{ ltb_token }}";'

    - name: "Configure ltb binddn"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$ldap_binddn = "cn=manager,dc=example,dc=com";'
        replace: '$ldap_binddn = "{{ ltb_binddn }}";'

    - name: "Configure ltb bindpw"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$ldap_bindpw = "secret";'
        replace: '$ldap_bindpw = "{{ ltb_bindpw }}";'

    - name: "Configure ltb base"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$ldap_base = "dc=example,dc=com";'
        replace: '$ldap_base = "{{ ltb_base }}";'

    - name: "Configure ltb mail_from"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$mail_from = "admin@example.com";'
        replace: '$mail_from = "{{ ltb_mail_from }}";'

    - name: "Configure ltb mail_from_name"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$mail_from_name = "Self Service Password";'
        replace: '$mail_from_name = "{{ ltb_mail_from_name }}";'

    - name: "Configure ltb mail_smtp_host"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$mail_smtp_host = ''localhost'''
        replace: '$mail_smtp_host = "{{ ltb_mail_smtp_host }}";'

    - name: "Configure ltb mail_smtp_user"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$mail_smtp_user = '''';'
        replace: '$mail_smtp_user = "{{ ltb_mail_smtp_user }}";'

    - name: "Configure ltb mail_smtp_pass"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$mail_smtp_pass = '''';'
        replace: '$mail_smtp_pass = "{{ ltb_mail_smtp_pass }}";'

    - name: "Configure ltb mail_smtp_port"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/conf/config.inc.local.php
        regexp: '\$mail_smtp_port = 25;'
        replace: '$mail_smtp_port = {{ ltb_mail_smtp_port }};'

    - name: "Configure ltb lang changehelp"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/lang/pt-BR.inc.php
        regexp: '\$messages\[''changehelp''\] = "Escreva a senha atual e escolha uma nova.";'
        replace: '$messages[''changehelp''] = "Digite a senha atual e escolha uma nova.";'

    - name: "Configure ltb lang changehelp"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/lang/pt-BR.inc.php
        regexp: '\$messages\[''emptychangeform''\] = "Change your password";'
        replace: '$messages[''emptychangeform''] = "Altera&ccedil;&atilde;o de senha";'

    - name: "Configure ltb lang emptysendtokenform"
      ansible.builtin.replace:
        path: /usr/ltb-project-self-service-password-1.3/lang/pt-BR.inc.php
        regexp: '\$messages\[''emptysendtokenform''\] = "Email a password reset link";'
        replace: '$messages[''emptysendtokenform''] = "Enviar um e-mail com um link para reset da sua senha";'

    - name: Restart Apache
      service:
        name: apache2.service
        state: restarted
