- hosts: all
  become: yes
  tasks:
    - name: Download pacemaker.conf
      get_url:
        url: "{{ git_source }}/lb/configs/pacemaker.conf"
        dest: /etc/zabbix/zabbix_agentd.d

    - name: Download zbx_pacemaker.sudoers
      get_url:
        url: "{{ git_source }}/lb/configs/zbx_pacemaker.sudoers"
        dest: /etc/sudoers.d
