#!/bin/bash
echo "$(date) Backup Samba database" > /tmp/drbd-snapshot.log
rm -r -f /var/lib/samba/backup/*.bz2
/usr/bin/samba-tool domain backup online --targetdir=/var/lib/samba/backup -UAdministrator --server=192.168.1.249 --password=<domain_password>
[ $? -eq 0 ]  || exit 1
rm -r -f /var/lib/samba/backup/tmp*

echo "$(date) Create snapshot" >> /tmp/drbd-snapshot.log
btrfs subvolume snapshot -r /var/lib/samba/ /var/lib/samba/.snapshots/backup
if [ -d "/var/lib/samba/.snapshots/backup" ]; then
        echo "$(date) Success snapshot" >> /tmp/drbd-snapshot.log
else
        echo "$(date) Fail snapshot" >> /tmp/drbd-snapshot.log
        exit 1
fi
exit 0

